---
- hosts: all
  sudo: true
  tasks:
    - name: install nginx
      apt: pkg=nginx state=latest
    - name: install phusion passenger repo key
      apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x561F9B9CAC40B2F7 state=present
    - name: install phusion passenger repo
      apt_repository: repo="deb https://oss-binaries.phusionpassenger.com/apt/passenger trusty main" state=present
    - name: update
      apt: update_cache=yes
    - name: install passenger
      apt: pkg=passenger state=latest
    - name: install nginx extras
      apt: pkg=nginx-extras state=latest
    - name: install git
      apt: pkg=git state=latest
    - name: install ruby-dev
      apt: pkg=ruby1.9.1-dev state=latest
    - name: install sqlite3-dev
      apt: pkg=libsqlite3-dev state=latest
    - name: install g++
      apt: pkg=g++ state=latest
